version: "3"

services:
  normal-app-db-host:
    image: mysql:5.7
    restart: "unless-stopped"
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
    ports:
      - "33066:3306"
    volumes:
      - /var/lib/mysql57-data:/var/lib/mysql
  redis:
    image: redis
    ports:
      - "63799:6379"
    volumes:
      - ./redis-data:/var/lib/redis/data
  normal-app:
    image: normal-app:dev
    restart: "unless-stopped"
    ports:
      - "3004:3000"
    environment:
      MYSQL_USER_NAME: "root"
      MYSQL_HOST: "normal-app-db-host"
      MYSQL_PASSWORD: "toor"
      MYSQL_HOST_PORT: "3306"
      REDIS_URL: "redis://redis:6379/0"
    command: bash -c "bundle install && bundle exec rails db:create db:migrate && rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - ./hls-data:/usr/src/app/hls-data
    depends_on:
      - normal-app-db-host
      - redis
    tty: true
    stdin_open: true
  sidekiq:
    build: .
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    environment:
      RAILS_ENV: "development"
      MYSQL_USER_NAME: "root"
      MYSQL_HOST: "normal-app-db-host"
      MYSQL_PASSWORD: "toor"
      MYSQL_HOST_PORT: "3306"
      REDIS_URL: "redis://redis:6379/0"
    links:
      - redis
      - normal-app
      - normal-app-db-host
    command: bash -c 'bundle install && bundle exec sidekiq'
  nginx:
    image: nginx-hls:dev
    environment:
      HLS_DOMAIN_NAME: "videos.localhost"
    volumes:
      - ./hls-data:/usr/src/app/hls-data
    ports:
      - 8080:80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    restart: unless-stopped
